version: '3.4'

services:
  catalogdb:
    image: mongo

  catalog_api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

volumes:
  mongo_data: